=begin
#Smart Data Management

#RESTful API that can be used to access Kannegiesser's master data back end.

OpenAPI spec version: 0.4.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::KeyValues
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'KeyValues' do
  before do
    # run before each test
    @instance = SwaggerClient::KeyValues.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeyValues' do
    it 'should create an instance of KeyValues' do
      expect(@instance).to be_instance_of(SwaggerClient::KeyValues)
    end
  end
end

