=begin
#Smart Data Management

#RESTful API that can be used to access Kannegiesser's master data back end.

OpenAPI spec version: 0.4.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ShortNameModelBase
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShortNameModelBase' do
  before do
    # run before each test
    @instance = SwaggerClient::ShortNameModelBase.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShortNameModelBase' do
    it 'should create an instance of ShortNameModelBase' do
      expect(@instance).to be_instance_of(SwaggerClient::ShortNameModelBase)
    end
  end
  describe 'test attribute "short_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

